#!/bin/bash

#Fix to add the notebook computer image for enrolment package users...

/bin/echo "Command: Image: /tmp/notebook-computer.png" >> /var/tmp/depnotify.log

#Make DEPNotify control file writeable by users

/bin/chmod 666 /var/tmp/depnotify.log
